---
# install and configure byobu

- name: configure byobu launch-by-default
  become: yes
  debconf:
    name: byobu
    question: byobu/launch-by-default
    value: true
    vtype: boolean
  when: byobu_launch_by_default

- name: install byobu
  become: yes
  apt: name=byobu state=present
